TA-16
EdwardMayk/AE-product-inventory-FE pull request #4
Opened 2023-03-28 17:43 UTC by xVANIC

2023-03-29 04:12 UTC, EdwardMayk requested changes

2023-03-29 04:12 UTC, EdwardMayk commented on src/components/registerForm.js
> +NOMBRE DIFERENTE AL INICIO Y EN LA LLAMADA
que es esto? codigo limpio por favor

2023-03-29 04:12 UTC, EdwardMayk commented on src/App.js
identacion

2023-04-01 02:49 UTC, EdwardMayk approved these changes

2023-04-01 02:49 UTC, SchuwiProfessional approved these changes

2023-04-01 02:49 UTC, merged